@host = http://localhost:5000
POST {{host}}/signup
Content-Type: application/json

{
    "username": "user2",
    "email": "user2@shank.com",
    "password": "12345678",
    "phone": "1234567890"
}
###
POST {{host}}/login
Content-Type: application/json

{
    "email": "user2@shank.com",
    "password": "12345678"
}
###
POST {{host}}/forgetpass
Content-Type: application/json

{
    "email": "user1@shank.com"
}
###
